services:
  - type: web
    name: smiback
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/smiback-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SUPABASE_URL
        value: jdbc:postgresql://aws-0-ca-central-1.pooler.supabase.com:5432/postgres?sslmode=require
      - key: SUPABASE_USERNAME
        value: postgres.wtqjyiknveiglquvxthl
      - key: SUPABASE_PASSWORD
        sync: false
      - key: JPA_DDL_AUTO
        value: update
      - key: JPA_SHOW_SQL
        value: false
      - key: JPA_FORMAT_SQL
        value: true
      - key: SECURITY_USERNAME
        value: admin
      - key: SECURITY_PASSWORD
        sync: false
      - key: SECURITY_ROLES
        value: ADMIN
      - key: SERVER_PORT
        value: 8080
      - key: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
        value: "3"

      - key: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
        value: "1"

      - key: SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT
        value: "10000"
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1